# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25438e2077f9a262146cf4e0baa6a1c4a5c1251de884f6b62476432aa2084e39589cd1e97e52332fd970a933815b2b3f106959699486ca5343a9385722e54b4d

test:
  secret_key_base: e37bc7224dd970091db32b7af036f3737c7bb31b128d5a78862b76fa7ed4b203f0015e5fad62c422604038fffd37bfa9546362ce470926db0186a8e496147815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
